### ISSUE TITLE
Cygwin start-up endless loop

### ISSUE THREAD

**Issue by robcookson** [shabiel/fis-gtm#13]
We have a browser-based EPOS application that we have ported to cygwin + GTM.
Unfortunately, sometimes when the Windows 10 Professional PC is rebooted a cygwin startup window is opened and goes into an endless loop and the window does not close (see attached).
Fortunately, if you manually close the window and manually request the application start-up procedure in cygwin the application springs to life.
It make be related but we also get intermittent MUTEXERR errors, possibly linked to Jobbed processes and the system can freeze until rebooted or sometimes with manual rundowns. Once this has occurred trying to use ^%G to list a global after entering the global name may hang. Sometimes a global can be partially listed and the MUTEXERR error occurs before completely shown. We are investigating this but any pointers would be welcomed.
thanks.
![cygwin_mumps_startup](https://cloud.githubusercontent.com/assets/24296212/20833615/85b76f20-b888-11e6-8ccf-9923acf1fbde.png)

**Comment by robcookson** [comment]
Sorry, GTM version is GT.M V6.3-000 CYGWIN x86.

**Comment by ChristopherEdwards** [comment]
This sounds like an issue I've noticed and did some debugging on. I haven't been able to dig deeper into the semaphore/mutex problem. I've gotten them locally when initially doing the port, but they were happing only occasionally and the section where it was happening would cause a retry - and it only happened occasionally. If you have some code that replicates it routinely that may help narrow down the issue. That was the problem with the code i was using - it happened so intermittently that it was impossible to get the stars to align so i could have a debugger hooked up when the error occurred.

**Comment by shabiel** [comment]
Hi Rob,

I apologize for my tardiness. I just saw this today. This is the major known issue in the Cygwin Port and I didn't want to commit any time to fix it. If you contact FIS, they may help you.

--Sam

**Comment by shabiel** [comment]
I just fixed this; if you load the latest release, you won't have the problem any more.
