### ISSUE TITLE
transcode-open/apt-cyg repo unavailable, breaking the instructions in README.cygwin.md

### ISSUE THREAD

**Issue by gjsjohnmurray** [shabiel/fis-gtm#8]
The repo at https://github.com/transcode-open/apt-cyg is unavailable because of a DMCA takedown notice (https://github.com/github/dmca/blob/master/2016-01-26-apt-cyg.md)

Instead I ran this command in my admin-level Windows command shell:

`c:\>choco install cyg-get`

Then this to install the packages we need:

`c:\>cyg-get wget git libelf0-devel zlib-devel libicu-devel libgpgme-devel libgpg-error-devel openssl-devel tcsh libncurses-devel gcc4-g++ gdb automake make flex bison libnettle-devel libnettle`

This enabled me to proceed.

**Comment by ChristopherEdwards** [comment]
Thanks for the report, I'll update the building page with some new instructions.

**Comment by shabiel** [comment]
Apt-Cyg is back!
